### ISSUE TITLE
Improve documentation for `ArrayDecorator`'s `maxItems`

### ISSUE THREAD

**Issue by giacomocavalieri** [mondrian-framework/mondrian-framework#20]
Right now it's not immediately apparent from the documentation of `ArrayDecorator` if its `maxItems` option is considered as an inclusive or exclusive upper limit.

As far as I can tell this would require:
- [ ] inspecting the validation step to see if the number is included or not in the upper limit
- [ ] updating the documentation with a better explanation of the expected behavior

**Comment by edobrb** [comment]
I'm copying the property names from the openapi specification (https://swagger.io/specification/v3/)

In this case the final s is missing (`maxItems`). I propose `maxItems` and to add `minItems`. Also as regards the semantics, I would keep that of openapi.

**Comment by edobrb** [comment]
Ok i've now see #19

**Comment by giacomocavalieri** [comment]
Ok! I'll update the issue to keep the name the same and just update the documentation :)
